/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _authenticatedRouteRouteImport } from './routes/(_authenticated)/route'
import { Route as _authRouteRouteImport } from './routes/(_auth)/route'
import { Route as _authenticatedIndexRouteImport } from './routes/(_authenticated)/index'
import { Route as _authRegisterRouteImport } from './routes/(_auth)/register'
import { Route as _authLoginRouteImport } from './routes/(_auth)/login'

const _authenticatedRouteRoute = _authenticatedRouteRouteImport.update({
  id: '/(_authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/(_auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedIndexRoute = _authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authenticatedRouteRoute,
} as any)
const _authRegisterRoute = _authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof _authLoginRoute
  '/register': typeof _authRegisterRoute
  '/': typeof _authenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof _authLoginRoute
  '/register': typeof _authRegisterRoute
  '/': typeof _authenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(_auth)': typeof _authRouteRouteWithChildren
  '/(_authenticated)': typeof _authenticatedRouteRouteWithChildren
  '/(_auth)/login': typeof _authLoginRoute
  '/(_auth)/register': typeof _authRegisterRoute
  '/(_authenticated)/': typeof _authenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/'
  id:
    | '__root__'
    | '/(_auth)'
    | '/(_authenticated)'
    | '/(_auth)/login'
    | '/(_auth)/register'
    | '/(_authenticated)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  _authenticatedRouteRoute: typeof _authenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(_authenticated)': {
      id: '/(_authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_auth)': {
      id: '/(_auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authenticated)/': {
      id: '/(_authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedIndexRouteImport
      parentRoute: typeof _authenticatedRouteRoute
    }
    '/(_auth)/register': {
      id: '/(_auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof _authRegisterRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/(_auth)/login': {
      id: '/(_auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof _authRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authLoginRoute: typeof _authLoginRoute
  _authRegisterRoute: typeof _authRegisterRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authLoginRoute: _authLoginRoute,
  _authRegisterRoute: _authRegisterRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface _authenticatedRouteRouteChildren {
  _authenticatedIndexRoute: typeof _authenticatedIndexRoute
}

const _authenticatedRouteRouteChildren: _authenticatedRouteRouteChildren = {
  _authenticatedIndexRoute: _authenticatedIndexRoute,
}

const _authenticatedRouteRouteWithChildren =
  _authenticatedRouteRoute._addFileChildren(_authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  _authenticatedRouteRoute: _authenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
