/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _authenticatedRouteRouteImport } from './routes/(_authenticated)/route'
import { Route as _authRouteRouteImport } from './routes/(_auth)/route'
import { Route as _authenticatedIndexRouteImport } from './routes/(_authenticated)/index'
import { Route as _authenticatedSettingsRouteImport } from './routes/(_authenticated)/settings'
import { Route as _authenticatedCreateRoomRouteImport } from './routes/(_authenticated)/create-room'
import { Route as _authRegisterRouteImport } from './routes/(_auth)/register'
import { Route as _authLoginRouteImport } from './routes/(_auth)/login'
import { Route as _authenticatedRoomsRoomRouteImport } from './routes/(_authenticated)/rooms/$room'

const _authenticatedRouteRoute = _authenticatedRouteRouteImport.update({
  id: '/(_authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/(_auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedIndexRoute = _authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authenticatedRouteRoute,
} as any)
const _authenticatedSettingsRoute = _authenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _authenticatedRouteRoute,
} as any)
const _authenticatedCreateRoomRoute =
  _authenticatedCreateRoomRouteImport.update({
    id: '/create-room',
    path: '/create-room',
    getParentRoute: () => _authenticatedRouteRoute,
  } as any)
const _authRegisterRoute = _authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authenticatedRoomsRoomRoute = _authenticatedRoomsRoomRouteImport.update({
  id: '/rooms/$room',
  path: '/rooms/$room',
  getParentRoute: () => _authenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof _authLoginRoute
  '/register': typeof _authRegisterRoute
  '/create-room': typeof _authenticatedCreateRoomRoute
  '/settings': typeof _authenticatedSettingsRoute
  '/': typeof _authenticatedIndexRoute
  '/rooms/$room': typeof _authenticatedRoomsRoomRoute
}
export interface FileRoutesByTo {
  '/login': typeof _authLoginRoute
  '/register': typeof _authRegisterRoute
  '/create-room': typeof _authenticatedCreateRoomRoute
  '/settings': typeof _authenticatedSettingsRoute
  '/': typeof _authenticatedIndexRoute
  '/rooms/$room': typeof _authenticatedRoomsRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(_auth)': typeof _authRouteRouteWithChildren
  '/(_authenticated)': typeof _authenticatedRouteRouteWithChildren
  '/(_auth)/login': typeof _authLoginRoute
  '/(_auth)/register': typeof _authRegisterRoute
  '/(_authenticated)/create-room': typeof _authenticatedCreateRoomRoute
  '/(_authenticated)/settings': typeof _authenticatedSettingsRoute
  '/(_authenticated)/': typeof _authenticatedIndexRoute
  '/(_authenticated)/rooms/$room': typeof _authenticatedRoomsRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/create-room'
    | '/settings'
    | '/'
    | '/rooms/$room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/create-room'
    | '/settings'
    | '/'
    | '/rooms/$room'
  id:
    | '__root__'
    | '/(_auth)'
    | '/(_authenticated)'
    | '/(_auth)/login'
    | '/(_auth)/register'
    | '/(_authenticated)/create-room'
    | '/(_authenticated)/settings'
    | '/(_authenticated)/'
    | '/(_authenticated)/rooms/$room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  _authenticatedRouteRoute: typeof _authenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(_authenticated)': {
      id: '/(_authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_auth)': {
      id: '/(_auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(_authenticated)/': {
      id: '/(_authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedIndexRouteImport
      parentRoute: typeof _authenticatedRouteRoute
    }
    '/(_authenticated)/settings': {
      id: '/(_authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _authenticatedSettingsRouteImport
      parentRoute: typeof _authenticatedRouteRoute
    }
    '/(_authenticated)/create-room': {
      id: '/(_authenticated)/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof _authenticatedCreateRoomRouteImport
      parentRoute: typeof _authenticatedRouteRoute
    }
    '/(_auth)/register': {
      id: '/(_auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof _authRegisterRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/(_auth)/login': {
      id: '/(_auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/(_authenticated)/rooms/$room': {
      id: '/(_authenticated)/rooms/$room'
      path: '/rooms/$room'
      fullPath: '/rooms/$room'
      preLoaderRoute: typeof _authenticatedRoomsRoomRouteImport
      parentRoute: typeof _authenticatedRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authLoginRoute: typeof _authLoginRoute
  _authRegisterRoute: typeof _authRegisterRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authLoginRoute: _authLoginRoute,
  _authRegisterRoute: _authRegisterRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface _authenticatedRouteRouteChildren {
  _authenticatedCreateRoomRoute: typeof _authenticatedCreateRoomRoute
  _authenticatedSettingsRoute: typeof _authenticatedSettingsRoute
  _authenticatedIndexRoute: typeof _authenticatedIndexRoute
  _authenticatedRoomsRoomRoute: typeof _authenticatedRoomsRoomRoute
}

const _authenticatedRouteRouteChildren: _authenticatedRouteRouteChildren = {
  _authenticatedCreateRoomRoute: _authenticatedCreateRoomRoute,
  _authenticatedSettingsRoute: _authenticatedSettingsRoute,
  _authenticatedIndexRoute: _authenticatedIndexRoute,
  _authenticatedRoomsRoomRoute: _authenticatedRoomsRoomRoute,
}

const _authenticatedRouteRouteWithChildren =
  _authenticatedRouteRoute._addFileChildren(_authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  _authenticatedRouteRoute: _authenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
